blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from blog.views import (
    create_blog_view,
    detail_post_view,
    edit_blog_view,
    like_post_view,
    unlike_post_view,
    remove_like_post_view,
    remove_unlike_post_view,
    create_comment_view,
    like_comment_view,
    unlike_comment_view,
    remove_like_comment_view,
    remove_unlike_comment_view,
    post_notification,
    delete_post_view,
    reply_comment_view,
    post_another_post_view,

)


urlpatterns = [
    path('create_post/', create_blog_view, name='create-post'),
    path('<slug>/', detail_post_view, name='detail-post'),
    path('<slug>/edit/', edit_blog_view, name='edit-post'),
    path('<slug>/delete/', delete_post_view, name='delete-post'),
    path('<slug>/like/', like_post_view, name='like-post'),
    path('<slug>/remove_like/', remove_like_post_view, name='remove-like-post'),
    path('<slug>/unlike/', unlike_post_view, name='unlike-post'),
    path('<slug>/remove_unlike/', remove_unlike_post_view, name='remove-unlike-post'),
    path('<slug>/comment/', create_comment_view, name='create-comment'),
    path('<post_slug>/post_to_post/', post_another_post_view, name='create-post-to-post'),
    path("<slug>/<int:comment_id>/comment/like_comment", like_comment_view, name='like-comment'),
    path("<slug>/<int:comment_id>/comment/unlike_comment", unlike_comment_view, name='unlike-comment'),
    path("<slug>/<int:comment_id>/comment/remove_like_comment", remove_like_comment_view, name='remove-like-comment'),
    path("<slug>/<int:comment_id>/comment/remove_unlike_comment", remove_unlike_comment_view, name='remove-unlike-comment'),


    path("show_notification/<int:notification_pk>/<int:post_pk>/", post_notification, name='show-notification'),

    path('create_reply/<comment_id>', reply_comment_view, name='reply-comment'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

colearn/urls.py
from django.contrib import admin
from django.urls import path, include
from personal.views import home_screen_view

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('blog/', include('blog.urls')),

    path('', home_screen_view, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings

from ckeditor.fields import RichTextField

def get_header_image_filepath(self, filename):
    return f'header_images/{self.pk}/{filename}'

class BlogPost(models.Model):
    title                   = models.CharField(max_length=50, null=False, blank=False)
    header_image            = models.ImageField(max_length=255, upload_to=get_header_image_filepath, null=True, blank=True)
    body                    = RichTextField(blank=True, null=True)
    tag                     = models.CharField(max_length=50)
    date_published          = models.DateTimeField(auto_now_add=True, verbose_name='date published')
    date_updated            = models.DateTimeField(auto_now=True, verbose_name='date updated')
    author                  = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug                    = models.SlugField(blank=True, unique=True)
    likes                   = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='likes_post', blank=True, null=True)
    unlikes                 = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='unlikes_post', blank=True, null=True)


    def total_likes(self):
        return self.likes.count()
    
    def total_unlikes(self):
        return self.unlikes.count()

    def __str__(self):
        return self.title


def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)


class Comment(models.Model):
    post                    = models.ForeignKey(BlogPost, related_name='comments', on_delete=models.CASCADE)
    author                  = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='comment_author', on_delete=models.CASCADE)
    body                    = models.TextField()
    date_added              = models.DateTimeField(auto_now_add=True)
    likes                   = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='likes_comment', blank=True)
    unlikes                 = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='unlikes_comment', blank=True)


    def total_likes(self):
        return self.likes.count()
    
    def total_unlikes(self):
        return self.unlikes.count()

    def __str__(self):
        return f"{self.post.title} - {self.author.username}"
    

class Notification(models.Model):
    ## 1-Like 2-Comment 3-Reply
    notification_type       = models.SmallIntegerField()
    to_user                 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='notification_to', on_delete=models.CASCADE, null=True)
    from_user               = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='notification_from', on_delete=models.CASCADE, null=True)
    post                    = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name="+", blank=True, null=True)
    comment                 = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name="+", blank=True, null=True)
    date                    = models.DateTimeField(default=timezone.now)
    user_has_seen           = models.BooleanField(default=False)
    



class Reply(models.Model):
    comment                     = models.ForeignKey(Comment, related_name='replies', on_delete=models.CASCADE)
    user                        = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    reply                       = models.TextField(max_length=2000)
    timestamp                   = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username
    

    @property
    def get_replies(self):
        return self.replies.all()


class PostToAnotherPost(models.Model):
    slug                    = models.SlugField(blank=True, unique=True)
    title                   = models.CharField(max_length=50, null=False, blank=False)
    header_image            = models.ImageField(max_length=255, upload_to=get_header_image_filepath, null=True, blank=True)
    body                    = RichTextField(blank=True, null=True)
    tag                     = models.CharField(max_length=50)
    date_published          = models.DateTimeField(auto_now_add=True, verbose_name='date published')
    date_updated            = models.DateTimeField(auto_now=True, verbose_name='date updated')
    author                  = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    likes                   = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='likes', blank=True, null=True)
    unlikes                 = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='unlikes', blank=True, null=True)
    post_to_post            = models.ForeignKey(BlogPost, related_name='reply_post', null=True, blank=True, on_delete=models.CASCADE)


    def total_likes(self):
        return self.likes.count()
    
    def total_unlikes(self):
        return self.unlikes.count()

    def __str__(self):
        return self.title


def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_blog_post_receiver, sender=PostToAnotherPost)

blog/views.py
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from blog.models import BlogPost, Notification, Comment, PostToAnotherPost, Reply
from blog.forms import CreateBlogPostForm, UpdateBlogPostForm, CreateCommentForm, CreateReplyForm, CreatePostAnotherPostForm
from account.models import Account
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from operator import attrgetter

POSTS_PER_PAGE = 10

def create_blog_view(request):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('must-authenticate')
    
    form = CreateBlogPostForm(request.POST, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        author = user
        obj.author = author
        obj.save()
        return redirect('home')
    else:
        print("asdasdasd")
    context['form'] = form


    return render(request, 'blog/create_post.html', context)


def delete_post_view(request,slug):
    post = BlogPost.objects.get(slug=slug)
    post.delete()

    return redirect('home')


def detail_post_view(request, slug):
    context = {}

    if not request.user.is_authenticated:
        return redirect('must-authenticate')

    try:
        blog_post = BlogPost.objects.get(slug=slug)
    except:
        print("Can not find blog post object")
        blog_post = []

    try:
        post_to_post = PostToAnotherPost.objects.get(slug=slug)
    except:
        print("Can not find post to post object")

    
    if blog_post:
        likes_count = blog_post.total_likes
        unlikes_count = blog_post.total_unlikes
        context['blog_post'] = blog_post
        context['likes_count'] = likes_count
        context['unlikes_count'] = unlikes_count
    elif post_to_post:
        likes_count = post_to_post.total_likes
        unlikes_count = post_to_post.total_unlikes
        context['blog_post'] = post_to_post
        context['likes_count'] = likes_count
        context['unlikes_count'] = unlikes_count

    return render(request, 'blog/detail_post.html', context)


def edit_blog_view(request, slug):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('must-authenticate')

    blog_post = get_object_or_404(BlogPost, slug=slug)

    if blog_post.author != user:
        return HttpResponse("<h1 class='display-2'>You are not the author of that post.</h1>")

    if request.POST:
        form = UpdateBlogPostForm(request.POST or None, instance=blog_post)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context['success_message'] = "Successfully Updated"
            blog_post = obj
            return redirect('detail-post', blog_post.slug)

    form = UpdateBlogPostForm(
        initial= {
            "title" : blog_post.title,
            "header_image" : blog_post.header_image,
            "body" : blog_post.body,
            "tag" : blog_post.tag,
        }
    )            

    context['form'] = form
    return render(request, 'blog/edit_post.html', context)


def get_blog_queryset(query=None):
    queryset = []
    queries = query.split(" ")
    for q in queries:
        posts = BlogPost.objects.filter(
            Q(title__icontains=q) |
            Q(body__icontains=q) |
            Q(tag__icontains=q)
        ).distinct()

        for post in posts:
            queryset.append(post)

    return list(set(queryset))


def like_post_view(request, slug):
    if not request.user.is_authenticated:
        return redirect('must-authenticate')
    
    post = get_object_or_404(BlogPost, slug=slug)
    post.likes.add(request.user)
    post.unlikes.remove(request.user)

    note = Notification()
    note.notification_type = 1
    note.to_user = post.author
    note.from_user = request.user
    note.post = post
    note.save()
    return HttpResponseRedirect(reverse('detail-post', args=[str(slug)]))


def remove_like_post_view(request, slug):
    if not request.user.is_authenticated:
        return redirect('must-authenticate')
    
    post = get_object_or_404(BlogPost, slug=slug)
    post.likes.remove(request.user)
    return HttpResponseRedirect(reverse('detail-post', args=[str(slug)]))


def unlike_post_view(request, slug):
    if not request.user.is_authenticated:
        return redirect('must-authenticate')
    
    post = get_object_or_404(BlogPost, slug=slug)
    post.likes.remove(request.user)
    post.unlikes.add(request.user)

    return HttpResponseRedirect(reverse('detail-post', args=[str(slug)]))


def remove_unlike_post_view(request, slug):
    if not request.user.is_authenticated:
        return redirect('must-authenticate')
    
    post = get_object_or_404(BlogPost, slug=slug)
    post.unlikes.remove(request.user)

    return HttpResponseRedirect(reverse('detail-post', args=[str(slug)]))


def create_comment_view(request,slug):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('must-authenticate')
    
    post = get_object_or_404(BlogPost, slug=slug)
    
    form = CreateCommentForm(request.POST or None)
    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.get(email=user.email)
        obj.author = author
        obj.post = post
        obj.save()

        note = Notification()
        note.notification_type = 2
        note.to_user = post.author
        note.from_user = user
        note.post = post
        note.save()

        return redirect('detail-post', slug)
    
    form = CreateCommentForm(
        initial= {
            "author" : user,
            "post" : post
        }
    ) 

    context['form'] = form


    return render(request, 'blog/create_comment.html', context)


def like_comment_view(request, slug, comment_id):
    if not request.user.is_authenticated:
        return redirect('must-authenticate')
    
    post = get_object_or_404(BlogPost, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.likes.add(request.user)
    comment.unlikes.remove(request.user)

    note = Notification()
    note.notification_type = 1
    note.to_user = comment.author
    note.from_user = request.user
    note.comment = comment
    note.save()

    return redirect('detail-post', slug)


def unlike_comment_view(request,slug, comment_id):
    if not request.user.is_authenticated:
        return redirect('must-authenticate')
    
    post = get_object_or_404(BlogPost, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.likes.remove(request.user)
    comment.unlikes.add(request.user)

    return HttpResponseRedirect(reverse('detail-post', args=[str(slug)]))


def remove_like_comment_view(request,slug, comment_id):
    if not request.user.is_authenticated:
        return redirect('must-authenticate')
    
    post = get_object_or_404(BlogPost, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.likes.remove(request.user)
    return HttpResponseRedirect(reverse('detail-post', args=[str(slug)]))


def remove_unlike_comment_view(request, slug, comment_id):
    if not request.user.is_authenticated:
        return redirect('must-authenticate')
    
    post = get_object_or_404(BlogPost, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.unlikes.remove(request.user)

    return HttpResponseRedirect(reverse('detail-post', args=[str(slug)]))


def post_notification(request, notification_pk, post_pk):
    context = {}

    notification = Notification.objects.get(pk=notification_pk)
    post = BlogPost.objects.get(pk=post_pk)

    notification.user_has_seen = True
    notification.save()

    return redirect('detail-post', post.slug)


def reply_comment_view(request, comment_id):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('must-authenticate')
    
    comment = get_object_or_404(Comment, pk=comment_id)

    form = CreateReplyForm(request.POST or None)

    if form.is_valid():
        obj = form.save(commit=False)
        obj.user = user
        obj.comment = comment
        obj.save()

        note = Notification()
        note.notification_type = 3
        note.to_user = comment.author
        note.from_user = user
        note.comment = comment
        note.save()
        return redirect('detail-post', comment.post.slug)
    else:
        print('asdasdasd')
    context['form'] = form
       
    return render(request, 'blog/create_reply.html', context)


def post_another_post_view(request, post_slug):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('must-authenticate')
    
    post = get_object_or_404(BlogPost, slug=post_slug)
    form = CreatePostAnotherPostForm(request.POST, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.author = user
        obj.post_to_post = post
        obj.save()

        note = Notification()
        note.notification_type = 2
        note.to_user = post.author
        note.from_user = user
        note.post = post
        note.save()

        return redirect('home')
    else:
        print("asdasdasd")
    context['form'] = form


    return render(request, 'blog/create_post_to_post.html', context)

templates/blog/create_comment.html
{% extends 'base.html' %}

{% block title %}Leaving a Comment{% endblock title %}

{% block content %}


   <div class="container text-center">
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}

        <button type="submit" class="btn btn-lg btn-info">Leave a Comment</button>
    </form>
   </div>


{% endblock content %}

templates/blog/create_post.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Create Post{% endblock title %}

{% block content %}

<style type="text/css">
    .create-form {
        width: 100%;
        max-width: 100%;
        padding: 15px;
        margin: auto;
    }

    .submit-button {
        max-width: 200px;
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-lg-7 offset-lg-1">
            <form class="create-form" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <!-- title -->
                <div class="form-group">
                    <label for="id_title">Title</label>
                    <input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required
                        autofocus>
                </div>

                <!--Header Image-->
                <div class="form-group">
                    <label for="id_title">Header Image</label>
                    {% render_field form.header_image class="form-control" placeholder="Choose a header image!" %}
                </div>
                
                <!--Tag-->
                <div class="form-group">
                    <label for="id_title">Post Tag</label>
                    {% render_field form.tag class="form-control" placeholder="Insert tag for your post!" %}
                </div>

                <!-- Body -->
                <div class="form-group">
                    <label for="id_body">Content</label>
                    {% render_field form.body class="form-control" placeholder="This post is about..." %}
                    {{form.media}}
                </div>

                <!-- Submit btn -->
                <div class="d-flex justify-content-center"><button class="submit-button btn btn-lg btn-outline-primary btn-block" type="submit">POST IT</button></div>
            </form>

            
        </div>
    </div>
</div>



{% endblock content %}

templates/blog/create_post_to_post.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Create Post{% endblock title %}

{% block content %}

<style type="text/css">
    .create-form {
        width: 100%;
        max-width: 100%;
        padding: 15px;
        margin: auto;
    }

    .submit-button {
        max-width: 200px;
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-lg-7 offset-lg-1">
            <form class="create-form" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <!-- title -->
                <div class="form-group">
                    <label for="id_title">Title</label>
                    <input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required
                        autofocus>
                </div>

                <!--Header Image-->
                <div class="form-group">
                    <label for="id_title">Header Image</label>
                    {% render_field form.header_image class="form-control" placeholder="Choose a header image!" %}
                </div>
                
                <!--Tag-->
                <div class="form-group">
                    <label for="id_title">Post Tag</label>
                    {% render_field form.tag class="form-control" placeholder="Insert tag for your post!" %}
                </div>

                <!-- Body -->
                <div class="form-group">
                    <label for="id_body">Content</label>
                    {% render_field form.body class="form-control" placeholder="This post is about..." %}
                    {{form.media}}
                </div>

                <!-- Submit btn -->
                <div class="d-flex justify-content-center"><button class="submit-button btn btn-lg btn-outline-primary btn-block" type="submit">POST IT</button></div>
            </form>

            
        </div>
    </div>
</div>



{% endblock content %}

templates/blog/create_reply.html
{% extends 'base.html' %}

{% block title %}Reply{% endblock title %}

{% block content %}

    <div class="container text-center mt-5">
        <form method="POST">
            {% csrf_token %}
            <h2>{{form.as_p}}</h2>

            <button type="submit" class='btn btn-success'>Reply</button>
        </form>
    </div>

{% endblock content %}

templates/blog/detail_post.html
{% extends 'base.html' %}

{% block title %}Post Details{% endblock title %}

{% block content %}
<style type="text/css">
	.card {
		max-width: 700px;
	}

	.container {
		padding: 20px;
	}

</style>

<div class="container">
	<div class="row">

		<!-- Blog Post -->
		<div class="card m-auto">
			<div class="card-header">
				<div class="row">
					<div class="col"><a
							href="{% url 'account' user_id=blog_post.author.id %}">{{blog_post.author.username}}</a>
					</div>
					<div class="col">
						{% if not request.user in blog_post.likes.all %}
						<form action="{% url 'like-post' blog_post.slug %}" method="POST">
							{% csrf_token %}
							<button type="submit" name="post_id" value="{{blog_post.id}}"
								class="btn btn-outline-success btn-sm mr-2">Like</button>
						</form>
						{% else %}
						<form action="{% url 'remove-like-post' blog_post.slug %}" method="POST">
							{% csrf_token %}
							<button type="submit" name="post_id" value="{{blog_post.id}}"
								class="btn btn-success btn-sm">Liked</button>
						</form>
						{% endif %}
					</div>
					<div class="col">
						{% if not request.user in blog_post.unlikes.all %}
						<form action="{% url 'unlike-post' blog_post.slug %}" method="POST">
							{% csrf_token %}
							<button type="submit" name="post_id" value="{{blog_post.id}}"
								class="btn btn-outline-danger btn-sm mr-2">Unlike</button>
						</form>
						{% else %}
						<form action="{% url 'remove-unlike-post' blog_post.slug %}" method="POST">
							{% csrf_token %}
							<button type="submit" name="post_id" value="{{blog_post.id}}"
								class="btn btn-danger btn-sm">Unliked</button>
						</form>
						{% endif %}
					</div>
					<div class="col">Tag: {{blog_post.tag}}</div>
				</div>
			</div>
			{% if blog_post.header_image %}
			<img class="card-img-top" src="{{blog_post.header_image.url}}" alt="header_image">
			{% else %}
			{% endif %}
			<div class="card-body mt-2 mb-2">
				<h2 class="card-title">{{blog_post.title}}</h2>
				<p class="card-text">
					<hr>
					{{blog_post.body|safe}}
				</p>
				{% if blog_post.author == request.user %}
				<a href="{% url 'edit-post' blog_post.slug %}"><button type="button" class="btn btn-outline-dark">Edit
						Post</button></a>
				<a href="{% url 'delete-post' blog_post.slug %}"><button type="button"
						class="btn btn-outline-danger">Delete Post</button></a>
				{% endif %}
			</div>
			<div class="card-footer text-muted">
				<div class="row d-flex justify-content-between">
					<div class="col">
						Likes: {{likes_count}} | Unlikes: {{unlikes_count}}
					</div>
				</div>
				<hr>
				Last Edit on {{blog_post.date_updated}} by {{blog_post.author.username}}
			</div>
		</div>

	</div>
</div>

<div class="container d-flex justify-content-center" >
	<div class="row">
		<div class="col"><a href="{% url 'create-comment' blog_post.slug %}"> <button class="btn btn-primary">Add Comment</button></a></div>
		<div class="col"><a href="{% url 'create-post-to-post' blog_post.slug %}"> <button class="btn btn-primary">Add Post</button></a></div>
	</div>
</div>

<!--Comment Division-->
<div class="container-fluid">
	<div class="container-fluid">
		<h2 class='text-center'>Comments</h2>
		{% if blog_post.comments.all %}
		{% for comment in blog_post.comments.all %}
		<div class="container">
			<div class="card m-auto">
				<div class="card-header">
					<div class="row">
						<div class="row">
							<div class="col"><a
									href="{% url 'account' user_id=comment.author.id %}">{{comment.author.username}}</a>
							</div>
							<div class="col">
								{% if not request.user in comment.likes.all %}
								<form action="{% url 'like-comment' blog_post.slug comment.id %}" method="POST">
									{% csrf_token %}
									<button type="submit" name="post_id" value="{{blog_post.id}}"
										class="btn btn-outline-success btn-sm mr-2">Like</button>
								</form>
								{% else %}
								<form action="{% url 'remove-like-comment' blog_post.slug comment.id %}" method="POST">
									{% csrf_token %}
									<button type="submit" name="post_id" value="{{blog_post.id}}"
										class="btn btn-success btn-sm">Liked</button>
								</form>
								{% endif %}
							</div>
							<div class="col">
								{% if not request.user in comment.unlikes.all %}
								<form action="{% url 'unlike-comment' blog_post.slug comment.id %}" method="POST">
									{% csrf_token %}
									<button type="submit" name="post_id" value="{{blog_post.id}}"
										class="btn btn-outline-danger btn-sm mr-2">Unlike</button>
								</form>
								{% else %}
								<form action="{% url 'remove-unlike-comment' blog_post.slug comment.id %}"
									method="POST">
									{% csrf_token %}
									<button type="submit" name="post_id" value="{{blog_post.id}}"
										class="btn btn-danger btn-sm">Unliked</button>
								</form>
								{% endif %}
							</div>
						</div>
					</div>
				</div>
				<div class="card-body">
					{{comment.body}}
				</div>
				<div class="card-footer">
					<div class="row">
						<div class="col">Likes: {{comment.total_likes}} | Unlikes: {{comment.total_unlikes}}</div>
						<div class="col"><a href="{% url 'reply-comment' comment.id %}"><button class='btn btn-primary'>Reply</button></a></div>
					</div>
				</div>
			</div>
			{% for reply in comment.replies.all %}
				<div class="card mt-2 ml-auto reply">
					<div class="card-header">{{reply.user.username}}</div>
					<div class="card-body">{{reply.reply}}</div>
					<div class="card-footer">
						<div class="row">
							<div class="col">{{reply.timestamp}}</div>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
		{% endfor %}
		{% endif %}
		{%if blog_post.reply_post.all %}
		{% for post in blog_post.reply_post.all %}
			{% include 'snippets/blog_post_snippet.html' with incoming_post=post  %}
		{% endfor %}
		{% endif %}
	</div>
</div>



{% endblock content %}

templates/blog/edit_post.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Edit Post{% endblock title %}

{% block content %}
<style type="text/css">
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" value="{{form.initial.title}}" required autofocus>
				</div>
				
				
				<!-- Header Image -->
				<div class="form-group">
					<label for="id_title">Header Image</label>
					{% render_field form.header_image class="form-control" placeholder="Choose a header image" %}
				</div>
				

                <!--Tag-->
                <div class="form-group">
                    <label for="id_title">Post Tag</label>
                    {% render_field form.tag class="form-control" placeholder="Insert tag for your post" %}
                </div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_body">Content</label>
					{% render_field form.body class="form-control" placeholder="This blog is about..." %}
					{{form.media}}
				</div>


				{% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
			</form>	
		</div>
	</div>
</div>


{% endblock content %}